# .cpanel.yml
# This file assumes you are running 'npm run build' locally
# and committing the resulting 'dist' directory to your Git repository.
---
deployment:
 tasks:
   # Set the deployment path using the correct cPanel username
   - export DEPLOYPATH=/home/sauchapter/public_html/

   # Copy the committed 'dist' directory contents to the deployment path.
   # Using rsync is generally preferred for copying contents efficiently.
   # If rsync is not available on your cPanel server, use the 'cp' alternative.

   # Option 1: Using rsync (recommended if available)
   # Copies contents of dist/* into DEPLOYPATH, overwriting existing files.
   # The --delete flag removes files from DEPLOYPATH that are no longer in dist/
   - /bin/rsync -av --delete dist/ $DEPLOYPATH

   # Option 2: Using cp (fallback - less efficient, doesn't delete old files)
   # Remove the '#' from the following line ONLY if rsync doesn't work.
   # - /bin/cp -Rf dist/* $DEPLOYPATH
