---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sauchapter/public_html/
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp -R src/* $DEPLOYPATH/src
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp vite.config.ts $DEPLOYPATH