[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# This ensures that routes like /about or /events work correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200